### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
Can i put a for/in loop in a prompt? Im trying to loop through my hash insead of each set_quesiton object

**Comment by halfghaninne** [comment]
You could potentially loop through each item in the hash in order to create a string of all of them, that is saved in a variable and then passed as an argument to `prompt()`. But I think doing that loop inside of `prompt()` is impossible, or at least ill-advised.

**Comment by clburns107** [comment]
see last commit - im not sure what the difference is between these and why it works for one but not the other?

**Comment by halfghaninne** [comment]
I took a _very_ cursory glance, but [this](https://github.com/clburns107/javascript-toy__quiz-part-1/blob/99f7edd841fa47c7ff73bea2c97b597f132fa779/global.js#L36) might be causing an issue. Let me know if that didn't get at the heart of the matter.

**Comment by clburns107** [comment]
Thank you for that catch but it didnt seem to fix the issue. From what i can tell it doesnt like when i try to call questions using the dynamic variable "quizQuestions[i]"  but it works just fine when i call q1 specifically and that makes NO sense to me...

**Comment by halfghaninne** [comment]
I'll take a closer look now.

**Comment by halfghaninne** [comment]
That _does_ seem strange. Have you been able to use `debugger;` on line 88 to take a look at what `quizQuestions` is and then bit-by-bit trying to recreate the work you do on line 89?

**Comment by clburns107** [comment]
yes if i call quizQuestions[0].options in the debugger it returns all of my options in a hash like i have them stored

**Comment by halfghaninne** [comment]
Ah. I would expect a for ... in loop to work for an Array. Does it work the same for a hash in JS? (It may; I'm genuinely asking as I investigate on my own).

**Comment by halfghaninne** [comment]
Ugh. Nope looks like you're using it correctly. Let me come over and try to be of more help.

**Comment by clburns107** [comment]
trying to reset form with .reset function but i get an error that says its not a function. am i calling it wrong?

**Comment by sumeetjain** [comment]
`.reset` is how you'd reset a `<form>` element (and all its children elements). For a single text field, just do `the_field.value = ""`.

**Comment by clburns107** [comment]
line 62 . having trouble getting my else if statement to run.  currentquestion is 4 and quizQuestions is 4 so why is it not running?

**Pull request closed without merging**
